services:
  db:
    image: "mysql:8.0"
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: job_san_development
      MYSQL_ROOT_PASSWORD: "password"
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_bin --default-authentication-plugin=mysql_native_password
  web:
    build: .
    volumes:
      - .:/usr/src/app
      - vendor_bundle:/user/src/app/vendor/bundle
      - tmp-data:/usr/src/app/tmp
      - public-data:/usr/src/app/public
    depends_on:
      - db
      - chrome
    environment:
      - SELENIUM_DRIVER_URL=http://selenium_chrome:4444/wd/hub
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec puma -C config/puma.rb"
  chrome:
    image: selenium/standalone-chrome:latest
    ports:
      - 4444:4444
  nginx:
    build: ./docker/nginx
    depends_on:
      - web
    ports:
      - "80:80"
    volumes:
      - ./public:/usr/share/nginx/html
      - tmp-data:/usr/src/app/tmp
      - public-data:/usr/src/app/public

volumes:
  vendor_bundle:
    driver: local
  public-data:
  tmp-data:
